version: '3.3'

x-build: &build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      VERSION: "1.0.0"

networks:
  custom_network:
    driver: bridge

services:
  firm_demo0_eim:
    <<: *build
    volumes:
      - sync_volume:/sync
      - type: bind
        source: bind/Client0/settings_client.ini
        target: /settings_client.ini
      - type: bind
        source: bind/data/100_a.csv
        target: /data/data.csv
    working_dir: /
    command:
      - /bin/bash
      - '-c'
      - |
        rm -f /sync/* && \
        ./matching ./settings_client.ini /data/data.csv && \
        touch /sync/firm_demo0_eim_done # 終了ファイルの作成
    networks:
      - custom_network

  firm_demo1_eim:
    <<: *build
    volumes:
      - sync_volume:/sync  # ボリュームを共有
      - type: bind
        source: bind/Client1/settings_client.ini
        target: /settings_client.ini
      - type: bind
        source: bind/data/100_b.csv
        target: /data/data.csv
    working_dir: /
    command:
      - /bin/bash
      - '-c'
      - |
        # NOTE: firm_demo0_eimと実行が被らないように終了ファイルを確認するまで実行しない
        while [ ! -f /sync/firm_demo0_eim_done ]; do sleep 1; done && \
        ./matching ./settings_client.ini /data/data.csv && \
        if [ $? -eq 0 ]; then \
          touch /sync/firm_demo1_eim_done; \
          rm -f /sync/firm_demo1_eim_failed; \
        else \
          touch /sync/firm_demo1_eim_failed; \
        fi
    depends_on:
      - firm_demo0_eim
    networks:
      - custom_network

  firm_demo1_synth:
    <<: *build
    volumes:
      - sync_volume:/sync  # ボリュームを共有
      - type: bind
        source: bind/Client1/settings_client.ini
        target: /settings_client.ini
      - type: bind
        source: bind/output
        target: /output
    working_dir: /
    command:
      - /bin/bash
      - '-c'
      - |
        # NOTE: firm_demo0_eimとfirm_demo1_eimの実行完了を確認するまで実行しない
        while [ ! -f /sync/firm_demo0_eim_done ] || [ ! -f /sync/firm_demo1_eim_done ]; do \
            if [ -f /sync/firm_demo1_eim_failed ]; then exit 1; fi && \
            sleep 1; \
        done && \
        ./synth ./settings_client.ini /output/model.pkl
    depends_on:
      - firm_demo0_eim
      - firm_demo1_eim
    networks:
      - custom_network

volumes:
  sync_volume:
    driver: local
